name: credo
on: [push]
jobs:
  credo:
    name: runner / credo
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Run Credo
          uses: omareltf/my-credo@v4
          with:
            args: --config-file /credo.exs
