name: credo
on: [push]
jobs:
  credo:
    name: runner / credo
    runs-on: ubuntu-latest
    steps:

        - name: Run Credo
          uses: sumup-bank/run-credo@v1
          with:
            args: --only readability,warning
