name: credo
on: [pull_request]
jobs:
  credo:
    name: runner / credo
    runs-on: ubuntu-latest
    steps:

        - name: Run Credo
          uses: sumup-bank/run-credo@v1
          with:
            args: --help
        - name: Create annotation for build error
          run: echo "::error file=app.js,line=1::Missing semicolon"
